huggingface/optimum-tpu

.github/workflows/check_code_quality.yml
Makefile
optimum/tpu/__init__.py
optimum/tpu/modeling.py
pyproject.toml
text-generation-inference/server/text_generation_server/generator.py

`TPUModelForX` becomes `AutoModelForX` to better match with transformers API

Adopt naming convention of transformers API

---

docs/source/index.mdx

Fix "runningo" instead of "running" in `index.mdx`

Fix typo in index.mdx

---

README.md
docs/source/howto/deploy.mdx

We need to provide the find-links option to pip to find libtpu on Google storage

Fix optimum-tpu pip install instructions

---

Makefile

Fix build_dist target, that was broken because depending on a file that does not exist anymore.

fix(build): setup.py removed from build_dist dependencies

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
.github/workflows/test-pytorch-xla-tpu-tgi.yml
.github/workflows/test-pytorch-xla-tpu.yml
examples/language-modeling/llama_tuning.md
pyproject.toml
requirements.txt
text-generation-inference/docker/Dockerfile
text-generation-inference/server/pyproject.toml
text-generation-inference/server/text_generation_server/generator.py

A rather uninteresting PR, that updates Pytorch and transformers dependency versions, and makes sure that everything still works as before.
This will however allow to integrate some features that have been integrated on PT2.3 and newer transformers vesions.

Update to Pytorch 2.3.0 and transformers v4.40.2

---

optimum/tpu/fsdp_v2.py
pyproject.toml

When fine-tuning Gemma-7B on Pytorch XLA 2.3.0, we saw and reported an issue: https://github.com/pytorch/xla/issues/7138
This seems to have been fixed on nightly. This commit relaxes dependency versions and displays a warning when getting FSDP training args for Gemma on 2.3.0.

chore(training): Allow training on torch xla > 2.3.0, add warning

---

docs/source/howto/serving.mdx

Correct server and port in docs for serving TGI.
Note that port redirection is removed because we use `--net=host`.

fix(doc): update server and port when serving TGI

---

optimum/tpu/modeling_mistral.py
pyproject.toml
text-generation-inference/server/pyproject.toml

- Add missing dependency on `sentencepiece` that is making the nightly CI fail.
- Serve mistral in `bfloat16` by default.

Mistral nits

---

optimum/tpu/version.py
text-generation-inference/server/text_generation_server/version.py

Simple bump to v0.1.0a1 to get a cleaner version for a container image.

chore: bump to version v0.1.0a1

---

.github/workflows/tpu-tgi-release.yml

Prepares CI to upload TGI image on TPUs.

feat(TGI): add release docker image build and push to registry workflow

---

.github/workflows/tpu-tgi-release.yml
text-generation-inference/docker/entrypoint.sh
text-generation-inference/server/pyproject.toml
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/server.py
text-generation-inference/server/text_generation_server/version.py
text-generation-inference/tests/test_generator_slot.py
text-generation-inference/tests/test_prefill_truncate.py

- Removed variables form entrypoint.sh, they are passed to the launcher via env vars
- Prevent issues with numpy 2.0 version
- correct TGI version
- add GKE ulimit command
- correct CachedBatch serialization when it's None (it was causing health call to crash)
- prefill and decode input pre-processing done in CPU to prevent wasting memory and time in compilation on TPU
- warmup clears after prefill
- fix clear implementation

Several Inference Endpoint fixes

---

.github/workflows/tpu-tgi-release.yml
optimum/tpu/version.py
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/generator_base.py
text-generation-inference/server/text_generation_server/version.py
text-generation-inference/tests/test_decode.py
text-generation-inference/tests/test_gpt2.py

- Fix clear request with an ID (it was causing a crash on server).
- Raise an error when there are too many requests (it should never happen, but it's good to handle that).
- Add more prefill lengths to warmup. It will take longer, but it will end up in faster inference for shorter prompts, at least until we find a better fix for bucketing and padding not working as expected.
- Image version set to 0.1.2 (ready for release).

Few more Inference Endpoints fixes

---

optimum/tpu/static_cache_xla.py
text-generation-inference/server/text_generation_server/generator.py

This is actually a ripoff of the work originally done as a contribution to transformers:
https://github.com/huggingface/transformers/pull/31129/
The original contribution has not been merged yet, but it shows lower memory usage and better performance on XLA. So I think it's worth adding it here.

feat(cache): use optimized StaticCache class for XLA

---

optimum/tpu/version.py
text-generation-inference/docker/entrypoint.sh
text-generation-inference/server/text_generation_server/version.py

This lowers the default batch size to 2 to avoid memory issues with some models, and increments version.

Lower TGI IE batch size

---

text-generation-inference/server/text_generation_server/generator.py

This handles very unlikely to happen exceptions and return empty prefill responses instead of crashing.

Handle selector exception

---

.github/workflows/tpu-tgi-release.yml
Makefile
text-generation-inference/server/Makefile

This will fix the TGI base image to 2.0.3. The protobuf has not changed, everything works the same and it's much cleaner than using a sha1.

chore(tgi): update TGI base image

---

.github/workflows/secrets-leak.yml

This should prevent the issues happening randomly on some commits when bash was having issues escaping some characters.
This is essentially a ripoff from this commit:
https://github.com/huggingface/transformers/pull/31663/commits/3af9e835e44c0acc6595da2db8bb9d28cf6115bf

feat(ci): set `fetch-depth: 0` in trufflehog checkout step

---

pyproject.toml

Removed direct dependency to a repo to avoid errors when publishing to pypi.

chore(pypi): remove direct dependency to doc-builder

---

.github/workflows/doc-build.yml
.github/workflows/doc-pr-build.yml

It cannot be added to pyproject.toml, otherwise it raises issues when uploading to pypi.

fix(ci): install doc builder explicitly

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
.github/workflows/test-pytorch-xla-tpu-tgi.yml
.github/workflows/test-pytorch-xla-tpu.yml

Now it has been released, it makes sense to use that version.
Without this, the CI was running the (moderate) risk of using an unstable/unreleased/unsupported version of torch and torch xla.

ci(docker): update torch-xla to 2.4.0

---

.github/workflows/test-pytorch-xla-tpu-tgi.yml
Makefile
README.md
optimum/tpu/__init__.py
optimum/tpu/fsdp_v2.py
optimum/tpu/generation/token_selector.py
optimum/tpu/jetstream_pt_support.py
optimum/tpu/version.py
pyproject.toml
text-generation-inference/server/Makefile
text-generation-inference/server/pyproject.toml
text-generation-inference/server/text_generation_server/auto_generator.py
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/__init__.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/compatibility.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/llama_model_exportable_hf.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/logits_process.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/token_selector.py
text-generation-inference/server/text_generation_server/server.py
text-generation-inference/tests/test_decode.py
text-generation-inference/tests/test_generator_slot.py
text-generation-inference/tests/test_gpt2.py
text-generation-inference/tests/test_prefill_truncate.py

This allows to use TGI with the `meta-llama/Llama-2-7b-hf` model using the Jetstream/Pytorch engine. 
This should be the starting point for a more complete integration in the future. It is not ready yet to replace the legacy implementation, in particular because:
- no other models have been tested, and some work is required for weights conversion;
- when I tried other Llama2 models it did not work, I still need to investigate the reason, this should follow next;
- further work should be done to simplify the coexistence of torch_xla and Jetstream/Pytorch. For now this feature is optional, in particular because the dependency installation is not that straightforward and execution of these two engines (Jetstream Pytorch and Pytorch/XLA) is exclusive.

✈️ Introduce Jetstream/Pytorch in TGI

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
optimum/tpu/model.py
pyproject.toml
text-generation-inference/server/text_generation_server/jetstream_pt_support/compatibility.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/tests/test_decode.py

Add support for Llama 3 (Llama 3.1 will come later), fixing some issues with some model settings. 
Also tests have been rearranged, so slow tests run with bigger models.

🦙 Llama3 on TGI - Jetstream Pytorch

---

.github/workflows/test-pytorch-xla-tpu-tgi-jetstream.yml
.gitignore
Makefile
install-jetstream-pt.sh
pyproject.toml
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/llama_model_exportable_hf.py
text-generation-inference/tests/test_decode.py

Text generation was not correct because the weights in the model were not correctly loaded. This is not something that it was easy to spot just looking at few tokens generated, and it was something that it was actually fixed already in the Jetstream/Pytorch code, but the fix hadn't been ported to optimum-tpu.
This fix implement the necessary weights changes, aligning to Jetstream Pytorch, and tests expected output has been modified accordingly.
~~I plan to submit a change directly to the Jetstream Pytorch project, so to be able to reuse their modeling code and avoid surprises like this one in the future~~. EDIT: I added a commit that uses the original model, so there will be no need to request a change.
Also, I changed the way we install Jetstream Pytorch, to make it more reliable, as the …

Fix generation using Jetstream Pytorch

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
optimum/tpu/model.py
text-generation-inference/tests/test_decode.py

Slow tests have been failing for a while, this should fix them:

Fix slow tests

---

.github/workflows/tpu-tgi-release.yml
Makefile
install-jetstream-pt.sh
pyproject.toml
requirements.txt
text-generation-inference/docker/Dockerfile
text-generation-inference/server/Makefile
text-generation-inference/server/text_generation_server/cli.py
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/tests/test_warmup.py

Many changes to prepare a proper TGI image compatible with Jetstream Pytorch.
In particular:
- torch default type set to bfloat16 (because that's what's used mostly in TPUs anyway).
- Make warmup prepare smallest size from bucket (that it was previously skipping).
- ignore common warnings in pytests to avoid cluttering tests outputs
- add jetstream installation step to TGI image
- update TGI image (refer to commit message for details)
- install torch for cpu to avoid installing the default gpu version when possible.

🧹 Cleanup and fixes for TGI

---

text-generation-inference/server/text_generation_server/auto_generator.py
text-generation-inference/server/text_generation_server/cli.py
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/server/text_generation_server/server.py
text-generation-inference/tests/test_warmup.py

- Handle `max_input_tokens` sever argument, that can reduce the cache size in Jetstream.
- Add `SKIP_WARMUP` parameter to the legacy Pytorch/XLA TGI to simply debug.

Small TGI enhancements

---

text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py

Previously it was attempting to use the sequence length, leading to larger allocation and useless graph compilations.

fix(TGI Jetstream Pt): prefill should be done with max input size

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
text-generation-inference/server/text_generation_server/generator.py

Fix nightly jetstream with a workaround to avoid OOM.

Fix ci nightly jetstream

---

.github/workflows/test-pytorch-xla-tpu-tgi-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
.github/workflows/test-pytorch-xla-tpu-tgi.yml
.github/workflows/test-pytorch-xla-tpu.yml

Move workflows to ephemeral TPUs running on kubernetes.

CI ephemeral TPUs

---

.github/workflows/test-pytorch-xla-tpu-tgi-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
.github/workflows/test-pytorch-xla-tpu-tgi.yml
.github/workflows/test-pytorch-xla-tpu.yml
Makefile

Mount Hub cache and fix CLI errors. This should have two consequences:
- Increased speed in testing, because models do not need to be downloaded each time,
- Increased available space, that could be otherwise saturated (that I suspect being the reason why the nightly tests have been failing lately).

⛰ CI: mount hub cache and fix issues with cli

---

text-generation-inference/docker/Dockerfile

Fix yet another place where the Jetstream Pytorch installation was broken.

fix(docker): correct jetstream installation in TGI docker image

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
docs/source/howto/deploy.mdx
docs/source/howto/serving.mdx
optimum/tpu/cli.py
text-generation-inference/docker/entrypoint.sh
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/tests/conftest.py
text-generation-inference/tests/decode_tests_utils.py
text-generation-inference/tests/test_decode.py
text-generation-inference/tests/test_decode_jetstream.py
text-generation-inference/tests/test_decode_jetstream_quant.py

This integrates the `int8` quantization on TGI as supported on Jetstream Pytorch. This allows to fit larger models for serving, such as `mistralai/Mixtral-8x7B-v0.1`.
Note that some unexpected behaviour has been observed on some prompts when using other models, such as `Llama-3-70B`, so a test has been added but the model is not considered ready for deployment with the current implementation.

Quantization Jetstream Pytorch

---

docs/source/howto/serving.mdx

This is just to fix a link in the documentation, pointing to the wrong page for the deploy documentation.
Fixes #113

fix(doc): correct link to deploy page

---

.github/workflows/test-pytorch-xla-tpu-tgi-jetstream.yml
optimum/tpu/version.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/token_selector.py
text-generation-inference/server/text_generation_server/version.py
text-generation-inference/tests/test_tinyllama.py

This PR includes several fixes for Jetstream Pytorch TGI implementation, including corrected support for batches and sampling strategy switch support.
This finally prepares for the upcoming 0.2.0 release, the first that will officially support Jetstream Pytorch TGI.

More Jetstream Pytorch fixes, prepare for release

---

.github/workflows/test-pytorch-xla-tpu-tgi-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
.github/workflows/test-pytorch-xla-tpu-tgi.yml
.github/workflows/test-pytorch-xla-tpu.yml
.github/workflows/tpu-tgi-release.yml
Makefile
optimum/tpu/__init__.py
optimum/tpu/cli.py
optimum/tpu/fsdp_v2.py
pyproject.toml
requirements.txt
text-generation-inference/docker/Dockerfile
text-generation-inference/server/Makefile
text-generation-inference/server/pyproject.toml
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/models/gemma_model_hf.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/models/mixtral_model_hf.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/token_selector.py

This contains many dependencies updates:
- Jetstream v0.2.4
- TGI v2.4.1
- Transformers v4.46.3
- Accelerate v1.1.1
- Pytorch and Pytorch XLA v2.5.1
- Safetensors v0.4.5
All these to update to newer versions. Required changes (some revealed by tests) were done accordingly.

⬆️ Update dependencies

---

.github/workflows/tpu-tgi-release.yml

There were extra quote characters causing errors.

fix(ci): correct TGI_VERSION definition in workflow

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
text-generation-inference/tests/test_decode_jetstream.py

There were 2 more issues with nightly tests, I hope this one will finish fixing them:
- `gemma-7b` results changed in Jetstream tests too after sampling changes.
- there was a pytest label selector missing.

Fix nightlies again

---

text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/token_selector.py
text-generation-inference/tests/decode_tests_utils.py
text-generation-inference/tests/test_decode_jetstream.py
text-generation-inference/tests/test_generator_slot.py

The generator was crashing when the request parameter container a repetition_penalty > 1.0. This was due to the logits processor expecting params to be torch tensors. 
So this is now fixed, and a test has been added to detect any possible regression.

🔂 Fix repetition penalty

---

Makefile
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/tests/test_decode_jetstream.py

When loading large models, weights are sharded across a mesh of TPUs,
splitting the original weights into smaller tensors, each one with the
same shape.
This is not possible, however, if the original weights shape is not
divisible across the number of TPUs, because it results in a smaller
tensor for the last TPU.
This change pads the tensor with zeros, making it splittable across the
TPUs.
I expected this to cause a change in the model, but apparently that is not the case, and the model still has the same shape and produces a correct output. I suspect this might be due to the way the weight is loaded on the mesh, and the fact that the model figures out the part it should use, but I hadn't got the change to try many "misaligned" models,
the only one I used here it works now. 
Fixes #67

Allow sharding fine tuned misaligned models

---

.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
README.md
docs/source/howto/serving.mdx
optimum/tpu/jetstream_pt_support.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/models/llama_model_exportable_hf.py
text-generation-inference/tests/conftest.py
text-generation-inference/tests/test_decode_jetstream.py
text-generation-inference/tests/test_decode_jetstream_quant.py

This PR mainly adds support for RoPE scaling to Jetstream Pytorch Llama models, that is required to support newer Llama models on TGI, such as Llama 3.1, Llama 3.2 and Llama 3.3.
Note that Llama3.3 is a 70B model, so quantization should be enabled to serve it.

🦙 Newer Llamas support

---

README.md
docs/source/howto/training.mdx

Since we tested optimum-tpu and TGI on v6e, we mention it.

doc(v6e): mention initial v6e support

---

.github/workflows/tpu-tgi-release.yml
Makefile
text-generation-inference/Cargo.toml
text-generation-inference/docker/Dockerfile
text-generation-inference/docker/entrypoint.sh
text-generation-inference/server/Makefile
text-generation-inference/server/build-requirements.txt
text-generation-inference/server/text_generation_server/cli.py
text-generation-inference/server/text_generation_server/generator.py
text-generation-inference/server/text_generation_server/jetstream_pt_support/generator.py

This bumps the TGI router version to v3.0.0. This was done by applying the changes that fixed some issues that were investigated in https://github.com/huggingface/optimum-neuron/pull/748.

Bump TGI version to v3.0.0

---

.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
Makefile
text-generation-inference/integration-tests/conftest.py
text-generation-inference/integration-tests/requirements.txt
text-generation-inference/integration-tests/test_model.py

This PR adds the TGI docker integration test to the CI. 
This is related to issue #124 about the new integration test for TGI.
Link to the new action execution: https://github.com/huggingface/optimum-tpu/actions/runs/12667037809/job/35299701615
Special thanks to @paulinebm for all the help debugging the CI 🙌

👷 Add integration test to the CI

---

.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly-jetstream.yml
.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml

Disable nightly tests by commenting out the cron, as we do not expect much activity on the repo for now. The `workflow_dispatch` is still available in case of need.

chore(ci): disable nightly tests
