.github/workflows/doc-build.yml, docs/source/howto/overview.mdx, docs/source/howto/serving.mdx, docs/source/index.mdx, docs/source/tutorials/overview.mdx
Needs to upgrade `pip` before installing the lib in the doc generation workflow.
=> Fix main doc build workflow

docs/source/howto/deploy.mdx
This PR adds a couple of links to the Cloud TPU documentation. This will allow customers reading the HF documentation to easily find more detailed information about Cloud TPUs.
=> Added some links to Cloud TPU documentation

optimum/tpu/version.py
Prepare for next release cycle
=> Bump version to 0.1.0.dev2

optimum/tpu/generation/token_selector.py, text-generation-inference/tests/test_gpt2.py
Fix TGI tests with `do_sample=True` again and try to stabilize them once again by setting the RNG seed of XLA.
=> Fix tests with do_sample=True

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml
Enables nightly CI
Fixes # (issue)
=> chore(ci): added workflow for nightly tests

.github/workflows/test-pytorch-xla-tpu-tgi-nightly.yml, Makefile
Try again to fix the nightly builds. Apparently this time it works: https://github.com/huggingface/optimum-tpu/actions/runs/8941338547
=> Try again to fix nightly builds

.github/workflows/doc-build.yml
keep doc in sync with source/doc folder. 
version regex to catch is a proposal to allow moving to versions "*.*.*a*".
=> Bug doc builder

examples/language-modeling/llama_tuning.md
=> Fix typo ; Update llama_tuning.md

text-generation-inference/docker/Dockerfile
Hey y'all, I'm excited to try out TGI on TPUs! I was building the docker image from the repo, and there is a minor misspelling in it. Thanks again for the hard work.
=> Minor fix for mispelled stage in TGI dockerfile.

pyproject.toml
This allows to have correct version generated.
=> fix(build): add missing setuptools_scm section

optimum/tpu/fsdp_v2.py
There was an incorrect usage of logging API.
=> fix(logging): correct logging usage

text-generation-inference/tests/test_gpt2.py
They are failing in CI after the base image has been changed.
=> fix(tests): fix decode sample expected outputs again

.github/workflows/secrets-leak.yml
correct secrets leak so it works on every push.
=> fix(ci): correct secrets leak workflow check

optimum/tpu/version.py
update version to prepare release
=> chore: bump to version v0.1.1

.github/workflows/secrets-leak.yml
Apparently there was a problem with indentation in the secret leak workflow, preventing it to work correctly. This is hopefully fixed...
=> Fix secret leak workflow

.github/workflows/pypi-release.yaml, optimum/tpu/version.py, pyproject.toml, requirements.txt, text-generation-inference/server/text_generation_server/version.py
A pypi release workflow was added previously to this repository, but it is not working, so I am trying to make this work:
- I set the Dev status to pre-alpha.
- I update the workflow to only push on pypi when the release is published, instead of matching a tag pattern. My idea is that I will tag a version, test it on pypi-test and then I can release it once it's tested.
=> Pypi release

README.md, text-generation-inference/server/text_generation_server/jetstream_pt_support/compatibility.py, text-generation-inference/server/text_generation_server/jetstream_pt_support/engine_loader.py, text-generation-inference/server/text_generation_server/jetstream_pt_support/gemma_model_hf.py, text-generation-inference/tests/test_decode.py, text-generation-inference/tests/test_warmup.py
Added support for gemma 7B and 2B with TGI and Jetstream Pytorch.
=> 💎 Gemma on TGI Jetstream Pytorch

Makefile, text-generation-inference/docker/Dockerfile
This PR refactor the optimum-tpu dockerfile to also support Google-Cloud-Containers.
This removes the need to maintain to different but similar Dockerfile in optimum-tpu and huggingface/Google-Cloud-Containers repo
I tested the 3 docker image (normal, IE and GCC) with test requests to make sure everything is still working as expected
=> ⚙️ Refactor TGI Dockerfile to support Google-Cloud-Containers as a target

docs/source/_toctree.yml, docs/source/howto/training.mdx, docs/source/supported-architectures.mdx
Surface Supported Models for inference and fine-tuning in the doc. A table might be more suited in the future if we support other tasks than text generation
=> Doc supported architecture

.github/workflows/doc-build.yml, optimum/tpu/version.py, text-generation-inference/docker/Dockerfile, text-generation-inference/integration-tests/conftest.py, text-generation-inference/server/text_generation_server/version.py
- Bump dev version
- Doc checks for dev version to update main doc.
=> Doc update main
